# ========== 自定义 ==========
proxy:
  enable: true
  host: 127.0.0.1
  port: 1080


# spring boot 启用调试模式
debug:  true


# ========== Spring ==========
spring:
  # Spring 数据库
  datasource:
    username: sa
    password: